[package]
name = "tensor"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
evolrs = { path = "../../", version = "*", features = ["non-nightly"] }
